# Generated by Django 3.2.13 on 2023-01-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('making_marriage_work', '0002_makingmarriageworkbooking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MakingMarriageWorkBooking',
            new_name='MakingMarriageWorkClassBooking',
        ),
    ]
