# Generated by Django 2.2.1 on 2020-01-01 20:42

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_midwife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midwife',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
    ]
