# Generated by Django 2.2.1 on 2020-01-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_midwife', '0002_auto_20200101_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midwife',
            options={'ordering': ['name'], 'verbose_name': 'Midwive'},
        ),
        migrations.AlterField(
            model_name='midwife',
            name='website_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='midwife',
            name='website_type',
            field=models.CharField(blank=True, choices=[('WEB', 'Website'), ('PROF', 'Profile'), ('FB', 'Facebook')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='midwife',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
