# Generated by Django 2.2.1 on 2020-01-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_midwife', '0003_auto_20200109_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midwife',
            options={'ordering': ['name']},
        ),
    ]
