# Generated by Django 2.2.1 on 2019-12-31 23:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_doula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doulainfo',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doulainfo',
            name='website_type',
            field=models.CharField(choices=[('WEB', 'Website'), ('PROF', 'Profile'), ('FB', 'Facebook')], max_length=25),
        ),
    ]
