# Generated by Django 2.2.1 on 2020-01-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_doula', '0002_auto_20191231_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='doulainfo',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
