# Generated by Django 2.2.1 on 2020-01-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_doula', '0003_doulainfo_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoulaInfo',
            new_name='Doula',
        ),
    ]
