# Generated by Django 2.2.1 on 2020-01-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childbirth_classes', '0002_auto_20191228_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='childbirthclass',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
