# Generated by Django 2.2.1 on 2020-01-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childbirth_classes', '0003_childbirthclass_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childbirthclass',
            options={'ordering': ['-start_date'], 'verbose_name': 'Childbirth Classe'},
        ),
    ]
