# Generated by Django 2.2.1 on 2020-01-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childbirth_classes', '0005_auto_20200116_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='childbirthclassbooking',
            name='partner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
