# Generated by Django 3.2.13 on 2023-01-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childbirth_classes', '0008_alter_childbirthclass_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childbirthclass',
            options={'ordering': ['-start_date'], 'verbose_name': 'Childbirth Classe'},
        ),
    ]
