# Generated by Django 2.2.1 on 2020-01-17 19:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(max_length=25, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
