# Generated by Django 2.2.1 on 2019-12-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoulaWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Doula Training Workshop', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('full_price', models.IntegerField(default=300)),
                ('discount_price', models.IntegerField(default=275)),
                ('deposit', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('start_date', 'end_date')},
            },
        ),
    ]
