# Generated by Django 2.2.1 on 2019-12-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20191222_1620'),
        ('doula_training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doulaworkshop',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='locations.Location'),
            preserve_default=False,
        ),
    ]
