# Generated by Django 2.2.1 on 2019-12-23 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doula_training', '0002_doulaworkshop_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doulaworkshop',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='locations.Location'),
        ),
    ]
