# Generated by Django 2.2.1 on 2019-12-23 16:35

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('doula_training', '0003_auto_20191223_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoulaWorkshopBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=5)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('date', models.DateField()),
                ('cost', models.IntegerField()),
                ('paid', models.IntegerField()),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
