# Generated by Django 2.2.1 on 2019-12-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doula_training', '0004_doulaworkshopbookings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoulaWorkshopBookings',
            new_name='DoulaWorkshopBooking',
        ),
    ]
