# Generated by Django 2.2.1 on 2019-12-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20191222_1620'),
        ('doula_training', '0005_auto_20191223_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='doulaworkshopbooking',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking_location', to='locations.Location'),
        ),
    ]
