# Generated by Django 2.2.1 on 2019-12-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doula_training', '0006_doulaworkshopbooking_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doulaworkshopbooking',
            name='date',
        ),
        migrations.AddField(
            model_name='doulaworkshopbooking',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doula_booking', to='doula_training.DoulaWorkshop'),
        ),
    ]
