# Generated by Django 2.2.1 on 2019-12-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doula_training', '0007_auto_20191226_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doulaworkshopbooking',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doulaworkshopbooking',
            name='paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
