# Generated by Django 2.2.1 on 2019-12-28 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doula_training', '0008_auto_20191226_0948'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doulaworkshopbooking',
            unique_together={('first_name', 'last_name', 'email', 'workshop')},
        ),
    ]
