# Generated by Django 2.2.1 on 2020-01-16 14:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('doula_training', '0010_doulaworkshop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doulaworkshopbooking',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
