# Generated by Django 3.2.13 on 2023-01-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bringing_baby_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bringingbabyhomeclass',
            options={'ordering': ['-start_date'], 'verbose_name': 'Bringing Baby Home Classe'},
        ),
        migrations.AlterField(
            model_name='bringingbabyhomeclass',
            name='class_type',
            field=models.CharField(choices=[('8_Week', 'Bringing Baby Home'), ('4_Week', 'Surviving to Thriving')], max_length=25),
        ),
    ]
