# Generated by Django 3.2.13 on 2023-01-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bringing_baby_home', '0003_bringingbabyhomeclassbooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bringingbabyhomeclassbooking',
            options={'ordering': ['last_name'], 'verbose_name': 'Bringing Baby Home Class Booking'},
        ),
    ]
