# Generated by Django 2.2.1 on 2019-12-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('location_address', models.CharField(max_length=200)),
                ('location_city', models.CharField(max_length=50)),
                ('location_state', models.CharField(max_length=2)),
                ('location_zip', models.CharField(max_length=5)),
            ],
        ),
    ]
