# Generated by Django 2.2.1 on 2019-12-22 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_name']},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('location_name', 'location_address')},
        ),
    ]
