# Generated by Django 2.2.1 on 2019-12-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20191222_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_lat',
            field=models.DecimalField(decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_lng',
            field=models.DecimalField(decimal_places=15, max_digits=18, null=True),
        ),
    ]
