# Generated by Django 2.2.1 on 2020-01-31 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
